### ISSUE TITLE
Update wheezy version check

### ISSUE THREAD

**Issue by mscdex** [johnraff/cb-netinstall#1]
Debian 7.1.0 is now out and the install script results in the warning about no wheezy installation found.

Perhaps [this](https://github.com/johnraff/cb-netinstall/blob/f2a08a4f0cc84bb541524a8a4bdcc129d536f762/install#L142) should instead just be a major version check?

**Comment by johnraff** [comment]
Thank you for the warning mscdex. The regular expression applied to /etc/debian_version will have to be loosened up a bit. I'll get to it later today.

**Comment by johnraff** [comment]
The regex is now:
'(wheezy|(^|[^a-zA-Z0-9.])7($|[^a-zA-Z0-9]))'
I'm hoping that will pass 7._._ while blocking things like 6.0.7

The change is now uploaded so I'm closing this issue. If there are still problems I'll re-open it.

Thanks again for your help!
